name: Publish to PyPI.org
on:
  push

jobs:
  release-pypi:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    environment:
      name: PyPI
      url: ${{ steps.set_url.outputs.env_url }}
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: wheels
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Publish
        env:
          MATURIN_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          pip install maturin
          maturin upload -u __token__ --skip-existing *
      - name: Set environment url
        id: set_url
        run: |
          VERSION=$(echo $GITHUB_REF | sed -e "s#refs/tags/v##g")
          echo "::set-output name=env_url::https://pypi.org/project/maturin/$VERSION"