name: Build and publish
on:
  push

jobs:
  publish:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - uses: PyO3/maturin-action@v1
        with:
          maturin-version: latest
          command: build
          args: --release

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages_dir: target/wheels/
