name: Build and publish
on:
  push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Run Docker container to compile into Python package
        uses: docker://ghcr.io/pyo3/maturin
        with:
          args: >-
            -v ${{ github.workspace }}:/io
            build --release
