name: Build and publish
on:
  push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      # - name: Print stuff
      #   run: ls

      - name: Run Docker container to compile into Python package
        uses: docker://ghcr.io/pyo3/maturin
        with:
          build-args: -v $(pwd):/io
          args: build --release
