name: Build and publish
on:
  push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - uses: PyO3/maturin-action@v1
        with:
          maturin-version: latest
          command: build
          args: --release

      # - name: Run Docker container to compile into Python package
      #   uses: ghcr.io/pyo3/maturin
      #   with:
      #     build-args: -v $(pwd):/io
      #     args: build --release
