name: Build and publish
on:
  push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: [ubuntu-latest, macos-latest]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - uses: PyO3/maturin-action@v1
        with:
          maturin-version: latest
          command: build
          args: --release
      
      - name: Upload wheels
        uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: target/wheels/

  publish:
    runs-on: ubuntu-latest
    needs: build 
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: wheels
          path: target/wheels
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages_dir: target/wheels/
