name: Test build
on:
  push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: [ubuntu-latest, macos-latest]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - uses: PyO3/maturin-action@v1
        with:
          maturin-version: latest
          command: build
          args: --release